-- AegisVPN Database Schema
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id VARCHAR(36) REFERENCES users(id) ON DELETE CASCADE,
  role_id VARCHAR(36) REFERENCES roles(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS vpn_servers (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  country_code VARCHAR(2) NOT NULL,
  country_name VARCHAR(100) NOT NULL,
  city VARCHAR(100) NOT NULL,
  public_ip VARCHAR(45) NOT NULL UNIQUE,
  wireguard_endpoint VARCHAR(255) NOT NULL,
  wireguard_public_key VARCHAR(100) NOT NULL,
  wireguard_port INT DEFAULT 51820,
  capacity_mbps INT DEFAULT 1000,
  current_load_pct INT DEFAULT 0,
  latency_ms INT DEFAULT 0,
  packet_loss_pct FLOAT DEFAULT 0.0,
  is_healthy BOOLEAN DEFAULT TRUE,
  active_peers_count INT DEFAULT 0,
  version VARCHAR(50) DEFAULT '1.0.0',
  last_health_check TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS devices (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  platform VARCHAR(50) NOT NULL,
  public_key VARCHAR(100) NOT NULL UNIQUE,
  allocated_ipv4 VARCHAR(45) NOT NULL UNIQUE,
  allocated_ipv6 VARCHAR(45) NOT NULL UNIQUE,
  is_revoked BOOLEAN DEFAULT FALSE,
  last_connection TIMESTAMP WITH TIME ZONE,
  last_handshake TIMESTAMP WITH TIME ZONE,
  current_server_id VARCHAR(36) REFERENCES vpn_servers(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vpn_peers (
  id VARCHAR(36) PRIMARY KEY,
  device_id VARCHAR(36) REFERENCES devices(id) ON DELETE CASCADE,
  server_id VARCHAR(36) REFERENCES vpn_servers(id) ON DELETE CASCADE,
  public_key VARCHAR(100) NOT NULL,
  allowed_ips VARCHAR(255) NOT NULL,
  preshared_key VARCHAR(100),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(device_id, server_id)
);

CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) REFERENCES users(id) ON DELETE CASCADE,
  refresh_token_hash VARCHAR(255) NOT NULL,
  ip_address VARCHAR(45),
  user_agent TEXT,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS server_metrics (
  id VARCHAR(36) PRIMARY KEY,
  server_id VARCHAR(36) REFERENCES vpn_servers(id) ON DELETE CASCADE,
  cpu_pct FLOAT NOT NULL,
  memory_pct FLOAT NOT NULL,
  bandwidth_rx_mbps FLOAT NOT NULL,
  bandwidth_tx_mbps FLOAT NOT NULL,
  active_peers INT NOT NULL,
  recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS security_events (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) REFERENCES users(id) ON DELETE SET NULL,
  event_type VARCHAR(100) NOT NULL,
  severity VARCHAR(20) NOT NULL,
  details TEXT,
  ip_address VARCHAR(45),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_events (
  id VARCHAR(36) PRIMARY KEY,
  actor_id VARCHAR(36) REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(100) NOT NULL,
  target_type VARCHAR(50) NOT NULL,
  target_id VARCHAR(36),
  changes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) REFERENCES users(id) ON DELETE CASCADE,
  tier VARCHAR(50) DEFAULT 'free', -- free, premium
  max_devices INT DEFAULT 5,
  status VARCHAR(20) DEFAULT 'active',
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
